Algoritmo "CalcularGorjeta"
//Desenvolver um programa que pergunte o valor da conta
//a ser paga no restaurante e exiba como resposta o
//valor com o acréscimo dos 10% da gorjeta do garçom
Var
valorConta, ValorGorjeta, total: Real


Inicio
escreva("Digite o Valor da conta: ")
Leia(valorconta)

Valorgorjeta <- valorConta * 0.10
total <- valorConta + Valorgorjeta

escreva("O valor da gorjeta é: ", ValorGorjeta)
escreva("O valor total a ser pago é: ",total)
FimAlgoritmo

Fimalgoritmo

