Algoritmo "semnome"
//Fazer um algoritmo que pergunte dois números e ao final apresente os seguintes valores: a soma dos dois
//números, a subtração do primeiro pelo segundo número, a subtração do segundo pelo primeiro número, a
//multiplicação entre os dois números, a divisão do primeiro pelo segundo número, e também o resto da divisão
//do primeiro pelo segundo número.
Var
primeiroNumero: real
segundoNumero: real
resto: Real



Inicio
escreva("Informe um numero:")
leia(primeiroNumero)
escreva("informe outro numero:")
leia(segundoNumero)

escreval(primeiroNumero+segundoNumero)
escreval(primeiroNumero-segundoNumero)
escreval(primeiroNumero*segundoNumero)
escreval(primeiroNumero/segundoNumero)
Escreva("Resto da divisão do primeiro pelo segundo: ", resto)


Fimalgoritmo